vich_uploader:
    db_driver: orm

    mappings:
       products:
           uri_prefix: /cv_candidature
           upload_destination: '%kernel.project_dir%/public/cv_candidature'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
